// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRJRI1mlxPOQSvUVkhUFF3WojW_cPSzMg',
    appId: '1:897816792583:web:412854efbc3323a4ae64a2',
    messagingSenderId: '897816792583',
    projectId: 'govi-ai',
    authDomain: 'govi-ai.firebaseapp.com',
    storageBucket: 'govi-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMKnZKLvgAh7fCJeZcpqIKhrwqVNG0Z3I',
    appId: '1:897816792583:android:986f313142b6dc3cae64a2',
    messagingSenderId: '897816792583',
    projectId: 'govi-ai',
    storageBucket: 'govi-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApKTHs3jweNoDFAEjP-qmPld5oYFxHi94',
    appId: '1:897816792583:ios:d6c4f2d66a60bd4bae64a2',
    messagingSenderId: '897816792583',
    projectId: 'govi-ai',
    storageBucket: 'govi-ai.firebasestorage.app',
    iosBundleId: 'com.example.goviAi',
  );
}
